server:
  servlet:
    context-path: /RogerSpringBootMongo

# 設定 mongoDB 連線資訊 (使用 Jasypt 加密)
spring:
  # data:
  #   mongodb:
  #     username: ENC(Hoy4AgRmLJXcHI+UH/XvdLyfj1+jQyYRG1NWFqanpkA=) # 使用 Jasypt 加密 (可使用 JasyptEncryptUtil.java 產生): 原為 myDbUser
  #     password: ENC(gGt1aiDXi5vLk8OFcRsbOyjfWxET/jzeFnW4AJU5J50=) # 使用 Jasypt 加密 (可使用 JasyptEncryptUtil.java 產生): 原為 myDbUser
  #     authentication-database: ENC(zv6TdgiR23knlcy5ePxyCKQqmiiW036h) # 使用 Jasypt 加密 (可使用 JasyptEncryptUtil.java 產生): 原為 admin
  #     database: myshinynewdb # 指定要連線的 mongodb database 名稱
  #     host: 127.0.0.1
  #     port: 27017
  #     auto-index-creation: true # 自動建立 INDEX

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Log4j2 配置 - 改用 XML 格式
logging:
  config: classpath:log4j2.yml

# Jasypt 加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:mySecretKey} # 加密密鑰，建議使用環境變量設置
    algorithm: PBEWithMD5AndDES # 加密演算法
    key-obtention-iterations: 1000 # 密鑰獲取迭代次數
    pool-size: 1 # 連接池大小
    provider-name: SunJCE # 提供者名稱
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator # salt 生成器類
    string-output-type: base64 # 字符串輸出類型

# 自訂參數
custom:
  mongodb:
    username: ENC(Hoy4AgRmLJXcHI+UH/XvdLyfj1+jQyYRG1NWFqanpkA=) # 使用 Jasypt 加密 (可使用 JasyptEncryptUtil.java 產生): 原為 myDbUser
    password: ENC(gGt1aiDXi5vLk8OFcRsbOyjfWxET/jzeFnW4AJU5J50=) # 使用 Jasypt 加密 (可使用 JasyptEncryptUtil.java 產生): 原為 myDbUser
    authentication-database: ENC(zv6TdgiR23knlcy5ePxyCKQqmiiW036h) # 使用 Jasypt 加密 (可使用 JasyptEncryptUtil.java 產生): 原為 admin
    database: myshinynewdb # 指定要連線的 mongodb database 名稱
    host: 127.0.0.1
    port: 27017